In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.7.1+cpu


#Introduction to Tensor

In [3]:
#scalar
#Pytorch tensort are created using torch.Tensor()
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
#A scalar has no dimensions
scalar.ndim

0

In [5]:
#Get tensort back as Python int
scalar.item()

7

In [6]:
#Vector 
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim
#Number of pairs of closing square brackets

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
#MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim


2

In [62]:
MATRIX.shape

torch.Size([2, 2])

In [63]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                         [3,6,9],
                         [2,4,5]]])
TENSOR
#These are the fundament building blocks of tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [64]:
TENSOR.ndim #Output is 3
TENSOR.shape #The output means we have 1 3x3 tensor

torch.Size([1, 3, 3])

In [65]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors
### Why random tensors? They are important because the way many neural networks learn is that they learn with tensorts full od random numbers and then aajust those random numbers to better represent the data

`Start with random numbers -> look at data -> update a random number -> look at the data -> update random numbers`

The data type for all the current ones are `torch.float32`

In [66]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])

In [67]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) #Height, Width , colour channels (R,G,B)
random_image_size_tensor.ndim

3

### Zeros and ones

In [68]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [69]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of Tensors and tensorts-like

In [70]:
#Using torch.arange()
#one_to_ten = torch.arange(1,11)
one_to_ten = torch.arange(start =1, end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [71]:
#Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Data Types

**Note :** Tensor dataypes is one of the 3 big errors you'll run into Pytorch and Deep Learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right devide

In [72]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, # What dataype is the tensor (e.g float32 or float16)
                               device=None, # What device is your tensor on (GPU or CPU)
                               requires_grad=False) # Whether or not to track gradients with this tensors operation
float_32_tensor

tensor([3., 6., 9.])

In [73]:
float_32_tensor.dtype
#THe default data type even if mentioned is float32

torch.float32

In [74]:
float_16_tensor = torch.tensor([3.0,6.0,9.0],dtype=torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [75]:
float_16_tensor * float_32_tensor #Some operations may run an error if the tensors are not right datatype

tensor([ 9., 36., 81.])

### Getting information from tensors (These are tensor attributes)

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [76]:
# Creat a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.5745, 0.9200, 0.3230, 0.8613],
        [0.0919, 0.3102, 0.9536, 0.6002],
        [0.0351, 0.6826, 0.3743, 0.5220]])

In [77]:
#Find out some details about tensor
print(some_tensor)
print(f"Data type: {some_tensor.dtype}")
print(f"Shape of Tensor: {some_tensor.shape}")
print(f"Device of Tensor: {some_tensor.device}") #By default it is on the CPU

tensor([[0.5745, 0.9200, 0.3230, 0.8613],
        [0.0919, 0.3102, 0.9536, 0.6002],
        [0.0351, 0.6826, 0.3743, 0.5220]])
Data type: torch.float32
Shape of Tensor: torch.Size([3, 4])
Device of Tensor: cpu


### Manipulating Tensors (Tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (Element-wise)
* Division
* Matrix multiplication

In [78]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [79]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [80]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [81]:
# Try out pytorch inbuilt functions 
torch.mul(tensor,10)
#torch.add(tensor,10)

tensor([10, 20, 30])

### Matrix Multiplication

Two main ways of performing multiplcation in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplcation (dot product)

There are two main rules that performing matrix multiplcation need to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) matmul (3, 2)` wont work
* `(2, 3) matmul (3, 2)` will work
* `(3, 2) matmul (2, 3)` will work

2. The resulting matrix has the shape of **outer dimensions**:
* `(2, 3) matmul (3, 2)` -> `(2, 2)`
* `(3, 2) matmul (2, 3)` -> `(3, 3)`

In [82]:
# Element wise mutiplication
print(f"tensor * tensor equals {tensor * tensor}")

tensor * tensor equals tensor([1, 4, 9])


In [83]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

### One of the most common errors in deep learning: Shape Errors

In [84]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])
torch.matmul(tensor_A,tensor_B) # We can also use torch.mm it is same as torch.matmul
#The output will generate error

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using **transpose**

A **transpose** switches the axes or dimensions of a given tensor

In [85]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shape of tensor_B = {tensor_B.T}")
print(f"Multiplying: {tensor_A.shape} x {tensor_B.shape} <- inner dimenstions must match")
print("Output: \n")
print(f"{torch.matmul(tensor_A,tensor_B.T)}")
print(f"Output shape: {torch.matmul(tensor_A,tensor_B.T).shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shape of tensor_B = tensor([[ 7,  8,  9],
        [10, 11, 12]])
Multiplying: torch.Size([3, 2]) x torch.Size([3, 2]) <- inner dimenstions must match
Output: 

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
Output shape: torch.Size([3, 3])


### Finding the min, max, mean, sum etc (tensor aggregation)

In [86]:
# Create a tensor
x = torch.arange(0,100,10)
torch.min(x) #x.min() is also possible

tensor(0)

In [87]:
torch.max(x) #x.max() is also possible

tensor(90)

In [ ]:
torch.mean(x)
#The tensor is of data type int64 or also known as LongTensor
#Mean method does not accept int64 or LongTensor as an input and thus generates and error of Invalid Data type

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
torch.mean(x.type(torch.float32))
#torch.mean() method usually takes float datatypes to work

tensor(45.)

In [33]:
torch.sum(x) #x.sum() also can be used

NameError: name 'x' is not defined

### Finding the positional min and max

In [34]:
x.argmin()
#At index 0 we get the value 0 which is the lowest number
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where the minimum value occurs

NameError: name 'x' is not defined

In [35]:
x.argmax()
# At index 9 we get the value 90 which is the highest number
# Find the position in tensor that has the maximu value with argmax() -> returns index position of target tensor where the maximum value occurs

NameError: name 'x' is not defined

### Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - Reshapes an input tensor to a defined shape
* View - return a view of input tensor of certain shape but keep the same memory as the original tensor
* stacking - combine multiple tensor on top of each other (vstack) or (hstack) virtual stack or horizontal stack
* Squueze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - return a view of theinput with dimensions permute (swapped) in a certain way

In [36]:
# Create a tensor
x = torch.arange(1.,10.)
x,x.dtype

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.float32)

In [37]:
# Add an extra dimension
x_reshape = x.reshape(1, 7)
x_reshape,x_reshape.shape
#Ouput will be error as we are trying to squeeze 9 elements into a tensor of size 7

RuntimeError: shape '[1, 7]' is invalid for input of size 9

In [38]:
x_reshape = x.reshape(1, 9)
x_reshape,x_reshape.shape
# Look at the extra square bracket added to the ouput tensor
#x_reshape = x.reshape(2, 9) wont work as 2 * 9 = 18 so we are trying to fit a tensor of size 9 into a tensor of size 18

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [39]:
x_reshape = x.reshape(9, 1)
x_reshape,x_reshape.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [40]:
x_reshape = x.reshape(1, 9)
x_reshape,x_reshape.shape

#The multiplication of the two input numbers must be equal to the number of numbers in the tensor

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [41]:
# Changing the view 
z = x.view(1, 9)
z,z.shape
#changing z changes x because a view of a tensor cshares the same memory as the orignal input

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [42]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [43]:
# torch.squeeze()
x_reshape.squeeze()

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [44]:
x_reshape.squeeze().shape #It removes all single dimensions
#Similarly x_reshape.unsqueeze().shape #Add an extra dimension with unsqueeze

torch.Size([9])

In [45]:
#torch.permute - rearranged the dimension of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) 
x_permuted = x_original.permute(2,0,1) #Sjofts axis 0->1, 1->2, 3->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") #[color_channels,height,width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


### Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with Numpy

In [46]:
# Create a tensor
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [47]:
# Lets index on our new tensor
x[0] #We have indexed on the 0th dimension

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [48]:
# Lets index on the middle bracket (dim=1)
x[0][0] #x[0,0]

tensor([1, 2, 3])

In [49]:
#Indexing on the most inner bracket
x[0][0][0]

tensor(1)

### PyTorch tensors and Numpy 

* Data in Numpy, want in PyTorch Tensor -> `torch.from_numpy(ndarray)`
* PyTorch Tensor -> NumPy -> `torch.Tensor.numpy()`

In [50]:
# Numpy array to tensor
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) 
array,tensor
# Numpy's default data type is Float64 and tensors default data type is Float32

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [51]:
# tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again... `

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**

Essentially what the random seed does is "flavour" the randomness

In [52]:
RANDOM_SEED = 42 #Could be any number 
torch.manual_seed(RANDOM_SEED)
tensor_A = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
tensor_B = torch.rand(3,4)
# The random seed will have to be set everytime a seed is used in Jupyter notebook. 
print(tensor_A)
print(tensor_B)
print(tensor_A == tensor_B)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
